############# German navigation ##############

# top menu
[[top]]
name = "NEWS"
pageRef = "/aktuelles"
weight = 1

[[top]]
name = "KONTAKT"
pageRef = "/pages/kontakt"
weight = 2

[[top]]
name = "SPENDEN"
pageRef = "/spenden/spenden"
weight = 3

[[top]]
name = "SPEISEPLAN"
url = "/pages/speiseplan"
weight = 4
[[top.params]]
icon = "fa fa-utensils"

[[top]]
name = "ELTERN-LOGIN"
url = "https://www.montessorischule-gilching.de/login"
weight = 5
[[top.params]]
icon = "fa fa-user-lock"


# main menu
[[main]]
name = "Startseite"
pageRef = "/"
weight = 1

[[main]]
name = "Unsere Schule"
weight = 2

[[main]]
name = "Konzept"
weight = 1
parent = "Unsere Schule"

[[main]]
name = "Qualitäten"
weight = 1
parent = "Konzept"
pageRef = "/schule/konzept/qualitaeten"

[[main]]
name = "Maria Montessori"
weight = 2
parent = "Konzept"

[[main]]
name = "Zur Person"
weight = 1
parent = "Maria Montessori"
pageRef = "/schule/konzept/maria-montessori/zur-person"

[[main]]
name = "Grundzüge der Pädagogik"
weight = 2
parent = "Maria Montessori"
pageRef = "/schule/konzept/maria-montessori/grundzuege-der-paedagogik"


[[main]]
name = "Schulhaus"
weight = 2
parent = "Unsere Schule"

[[main]]
name = "Haus"
weight = 1
parent = "Schulhaus"
pageRef = "/schule/schulhaus/haus"

[[main]]
name = "Küche"
weight = 2
parent = "Schulhaus"
pageRef = "/schule/schulhaus/kueche"

[[main]]
name = "Schulgeld"
weight = 3
parent = "Schulhaus"
pageRef = "/schule/schulhaus/schulgeld"

[[main]]
name = "Schulordnung"
weight = 4
parent = "Schulhaus"
pageRef = "/schule/schulhaus/schulordnung"

[[main]]
name = "Verwaltung"
weight = 3
parent = "Unsere Schule"
pageRef = "/schule/verwaltung"

[[main]]
name = "Pädagogisches Team"
weight = 4
parent = "Unsere Schule"
pageRef = "/schule/paedagogisches-team"

[[main]]
name = "Schüler*innen"
weight = 5
parent = "Unsere Schule"
pageRef = "/schule/schuelerinnen"

[[main]]
name = "Elternengagement"
weight = 6
parent = "Unsere Schule"

[[main]]
name = "Elternbeirat"
weight = 1
parent = "Elternengagement"
pageRef = "/schule/elternengagement/elternbeirat"

[[main]]
name = "AGs und Dienste"
weight = 2
parent = "Elternengagement"
pageRef = "/schule/elternengagement/ags-und-dienste"

[[main]]
name = "Aufnahme"
weight = 3

[[main]]
name = "Anmeldeunterlagen"
weight = 1
parent = "Aufnahme"
pageRef = "/aufnahme/anmeldeunterlagen"

[[main]]
name = "Schulgeld"
weight = 2
parent = "Aufnahme"
pageRef = "/aufnahme/schulgeld"

[[main]]
weight = 4
name = "Spenden und Förderer"

[[main]]
weight = 1
parent = "Spenden und Förderer"
name = "Förderer"
pageRef = "/spenden/foerderer"

[[main]]
weight = 2
parent = "Spenden und Förderer"
name = "Spenden"
pageRef = "/spenden/spenden"

[[main]]
weight = 5
name = "Verein"

[[main]]
weight = 1
parent = "Verein"
name = "Vorstand"
pageRef = "/verein/vorstand"

[[main]]
weight = 2
parent = "Verein"
name = "Satzung"
pageRef = "/verein/satzung"

[[main]]
weight = 6
name = "Karriere"
pageRef = "/pages/karriere"

[[main]]
weight = 7
name = "Presse"
pageRef = "/pages/presse"


# footer menu
[[footer]]
name = "Impressum"
pageRef = "/pages/impressum"
weight = 1

[[footer]]
name = "Datenschutzerklärung"
pageRef = "/pages/datenschutz"
weight = 2

[[footer]]
name = "login"
url = "https://www.montessorischule-gilching.de/login"
weight = 3
