############# German navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "News"
pageRef = "/news"
weight = 2

[[main]]
name = "Kontakt"
pageRef = "/contact"
weight = 3

[[main]]
weight = 4
name = "Spenden"
pageRef = "/spenden"

[[main]]
parent = "Spenden"
name = "Förderer"
pageRef = "/spenden/foerderer"


[[main]]
weight = 5
name= "Schule"

[[main]]
weight = 6
name = "Intern"
pageRef = "/intern"

[[main]]
weight = 7
parent = "Schule"
name = "Arbeitsgruppen & Elterndienste"
pageRef = "/schule/eltern/arbeitsgruppen_und_elterndienste"

# footer menu
[[footer]]
name = "Impressum"
pageRef = "/impressum"
weight = 1

[[footer]]
name = "Datenschutzerklärung"
pageRef = "/datenschutzerklaerung"
weight = 2

[[footer]]
name = "login"
pageRef = "/login"
weight = 3