############# German navigation ##############

# top menu
[[top]]
name = "NEWS"
pageRef = "/news"
weight = 1

[[top]]
name = "KONTAKT"
pageRef = "/contact"
weight = 2

[[top]]
name = "SPENDEN"
pageRef = "/spenden"
weight = 3

[[top]]
name = "ELTERN-LOGIN"
url = "https://www.montessorischule-gilching.de/login"
weight = 4
[[top.params]]
icon = "fa fa-user-lock"


# main menu
[[main]]
name = "Startseite"
pageRef = "/"
weight = 1

[[main]]
name = "News"
pageRef = "/news"
weight = 2

[[main]]
name = "Kontakt"
pageRef = "/contact"
weight = 3

[[main]]
weight = 4
name = "Spenden"
pageRef = "/spenden"

[[main]]
weight = 5
parent = "Spenden"
name = "Förderer"
pageRef = "/spenden/foerderer"


[[main]]
weight = 6
name = "Schule"
pageRef = "/schule"

[[main]]
weight = 7
parent = "Schule"
name = "Elternengagement"
pageRef = "/schule/eltern"

[[main]]
weight = 8
parent = "Elternengagement"
name = "Arbeitsgruppen & Elterndienste"
pageRef = "/schule/eltern/arbeitsgruppen_und_elterndienste"

# footer menu
[[footer]]
name = "Impressum"
pageRef = "/impressum"
weight = 1

[[footer]]
name = "Datenschutzerklärung"
pageRef = "/datenschutzerklaerung"
weight = 2

[[footer]]
name = "login"
url = "https://www.montessorischule-gilching.de/login"
weight = 3
