######################## default configuration ####################
baseURL = "/"
title = "Montessori Schule Gilching (München West)"
timeZone = "Europe/Berlin"
summaryLength = 10
hasCJKLanguage = false
defaultContentLanguage = "de"

########################### Services #############################
[services]
  [services.disqus]
    shortname = "themefisher-template"

########################## Permalinks ############################
[permalinks.page]
  pages = "/:slugorcontentbasename/"

[permalinks.section]
  elternengagement = "/elternengagement/"

########################## Pagination ############################
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

############################# Build ##############################
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

############################# Module #############################
[module]
  [module.hugoVersion]
    extended = true
    min = "0.141.0"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    disableWatch = true
    source = "hugo_stats.json"
    target = "assets/notwatching/hugo_stats.json"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/search"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/pwa"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/images"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/videos"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/icons/font-awesome"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/gzip-caching"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/accordion"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/table-of-contents"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/tab"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/modal"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/gallery-slider"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/components/preloader"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/components/social-share"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/components/cookie-consent"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/components/announcement"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/components/custom-script"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/components/render-link"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/shortcodes/button"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"

  [[module.imports]]
    path = "github.com/gethugothemes/hugo-modules/seo-tools/basic-seo"

############################# Related #############################
[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

############################# Outputs ############################
[outputs]
  home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################
[imaging]
  quality = 80
  resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

############################ Markup ##############################
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNumbersInTable = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = true

########################### Media types ###########################
[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]

########################### Output Format ##########################
[outputFormats]
  [outputFormats.WebAppManifest]
    mediaType = "application/manifest+json"
    rel = "manifest"
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true

########################### Languages ##############################
[languages]
  [languages.de]
    languageName = "Deutsch"
    languageCode = "de-DE"
    contentDir = "content/de"
    weight = 1

############################# Menus ################################
    [[languages.de.menus.top]]
      name = "Home"
      pageRef = "/"
      weight = 1

    [[languages.de.menus.top]]
      name = "Schule"
      pageRef = "/schule"
      weight = 2

    [[languages.de.menus.top]]
      name = "Elternarbeit"
      pageRef = "/elternengagement"
      weight = 3

    [[languages.de.menus.top]]
      name = "Spenden"
      pageRef = "/spenden"
      weight = 4

    [[languages.de.menus.top]]
      name = "Verein"
      pageRef = "/verein"
      weight = 5

    [[languages.de.menus.top]]
      name = "Speiseplan"
      pageRef = "/speiseplan"
      weight = 6
      [languages.de.menus.top.params]
        icon = "fa fa-utensils"

    [[languages.de.menus.top]]
      name = "Eltern-Login"
      url = "https://www.montessorischule-gilching.de/login"
      weight = 7
      [languages.de.menus.top.params]
        icon = "fa fa-user-lock"

    [[languages.de.menus.main]]
      name = "Startseite"
      pageRef = "/"
      weight = 1

    [[languages.de.menus.main]]
      name = "Schule"
      pageRef = "/schule"
      weight = 2

    [[languages.de.menus.main]]
      name = "Elternengagement"
      pageRef = "/elternengagement"
      weight = 3

    [[languages.de.menus.main]]
      name = "Spenden"
      pageRef = "/spenden"
      weight = 4

    [[languages.de.menus.main]]
      name = "Verein"
      pageRef = "/verein"
      weight = 5

    [[languages.de.menus.main]]
      name = "Karriere"
      weight = 6
      pageRef = "/pages/karriere"

    [[languages.de.menus.main]]
      name = "Presse"
      weight = 7
      pageRef = "/pages/presse"

    [[languages.de.menus.footer]]
      name = "Impressum"
      pageRef = "/pages/impressum"
      weight = 1

    [[languages.de.menus.footer]]
      name = "Datenschutzerklärung"
      pageRef = "/pages/datenschutz"
      weight = 2

    [[languages.de.menus.footer]]
      name = "Kontakt"
      pageRef = "/pages/kontakt"
      weight = 3

    [[languages.de.menus.footer]]
      name = "Presse"
      pageRef = "/pages/presse"
      weight = 4

    [[languages.de.menus.footer]]
      name = "Login"
      url = "https://www.montessorischule-gilching.de/login"
      weight = 5

############################# Params ###############################
[params]
  favicon = "images/favicon-96x96.png"
  logo = "images/logo-montessorischulegilching.gif"
  logo_width = "88px"
  logo_height = "118px"
  logo_webp = true
  logo_text = "Montessori Schule Gilching"
  header_image_banner = "images/header-zaun.jpg"
  navbar_fixed = true
  theme_switcher = false
  theme_default = "light"
  mainSections = ["aktuelles"]
  contact_form_action = "#"
  custom_script = ""
  copyright = "© Montessori Schule Gilching (Münchner Westen)"

  [params.preloader]
    enable = false
    preloader = ""

  [params.navigation_button]
    enable = false
    label = "Kontakt"
    link = "contact"

  [params.search]
    enable = false
    primary_color = "#121212"
    include_sections = ["aktuelles"]
    show_image = true
    show_description = true
    show_tags = true
    show_categories = true

  [params.announcement]
    enable = false
    expire_days = 7
    content = "You must replace the **baseURL** in **hugo.toml** file when deploying, you can manage this announcement from the **params.toml** file."

  [params.metadata]
    keywords = ["Montessori", "Grundschule", "Schule", "Gilching", "München", "Westen"]
    description = "Montessori Schule Gilching (München Westen)"
    author = "Monrtessori Schule Gilching"

  [params.site_verification]
    google = ""
    bing = ""
    baidu = ""
    facebook = ""
    mastodon = ""

  [params.cookies]
    enable = false
    expire_days = 60
    content = "This site uses cookies. By continuing to use this website, you agree to their use."
    button = "I Accept"

  [params.mermaid]
    js_url = "https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs"

  [params.widgets]
    sidebar = ["categories", "tags"]

  [params.google_map]
    enable = false
    map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
    map_latitude = "51.5223477"
    map_longitude = "-0.1622023"
    map_marker = "images/marker.png"

  [params.subscription]
    enable = false
    mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
    mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

############################# Plugins ##############################
  [[params.plugins.css]]
    link = "plugins/swiper/swiper-bundle.css"
    lazy = true

  [[params.plugins.css]]
    link = "plugins/glightbox/glightbox.css"
    lazy = true

  [[params.plugins.css]]
    link = "plugins/font-awesome/v6/brands.css"
    lazy = true

  [[params.plugins.css]]
    link = "plugins/font-awesome/v6/solid.css"
    lazy = true

  [[params.plugins.css]]
    link = "plugins/font-awesome/v6/icons.css"
    lazy = true

  [[params.plugins.css]]
    link = "https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/9.3.0/mmenu.min.css"
    lazy = false

  [[params.plugins.js]]
    link = "js/search.js"
    lazy = false

  [[params.plugins.js]]
    link = "plugins/swiper/swiper-bundle.js"
    lazy = false

  [[params.plugins.js]]
    link = "plugins/cookie.js"
    lazy = false

  [[params.plugins.js]]
    link = "plugins/glightbox/glightbox.js"
    lazy = true

  [[params.plugins.js]]
    link = "js/gallery-slider.js"
    lazy = true

  [[params.plugins.js]]
    link = "js/accordion.js"
    lazy = true

  [[params.plugins.js]]
    link = "js/tab.js"
    lazy = true

  [[params.plugins.js]]
    link = "js/modal.js"
    lazy = true

  [[params.plugins.js]]
    link = "plugins/youtube-lite.js"
    lazy = true
