backend:
  name: github
  repo: behboud/monte-web
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.b-kalantary.workers.dev
  commit_messages:
    create: Create {{collection}} {{slug}} {{author-name}}
    update: Update {{collection}} {{slug}} {{author-name}}
    delete: Delete {{collection}} {{slug}} {{author-name}}
    uploadMedia: Upload {{path}} {{author-name}}
    deleteMedia: Delete {{path}} {{author-name}}
    openAuthoring: "{{message}} {{author-name}}"
site_url: "https://behboud.github.io/monte-web/"
media_folder: /assets/images
public_folder: /images
display_url: "https://behboud.github.io/monte-web/"
logo_url: /monte-web/images/logo-montessorischulegilching.gif
locale: "de"
collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "data/social.json"
        label: Social Media
        name: social_media
        fields:
          - label: List of Social Media links
            name: main
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon (Font Awesome), name: icon, widget: string }
              - { label: Link, name: link, widget: string }
      - file: "hugo.toml"
        label: Site Config
        name: config
        editor:
          preview: false
        fields:
          - { label: Site Title for Browser Tab, name: title, widget: string }
  - name: "aktuelles"
    label: "Aktuelles"
    folder: "content/de/aktuelles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum Veröffentlichung", name: "publishdate", widget: "datetime" }
      - { label: "Stimmungsbild", name: "image", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - name: "tags"
        widget: "select"
        label: "Tags"
        multiple: true
        create: true
        options: ["Mitglieder", "Termin", "Projekt", "Verein"]
      - { label: "Inhalt", name: "body", widget: "markdown" }
      - { label: "Datum", name: "date", widget: "hidden", default: "{{now}}" }
  - name: "start"
    label: "Startseite"
    editor:
      preview: false
    files:
      - label: "Startseite"
        name: "index"
        file: "content/de/_index.md"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Untertitel", name: "content", widget: "string", required: false }
              - { label: "Bild", name: "image", widget: "image" }
          - label: "Slider Gallery"
            name: "slider"
            widget: object
            fields:
              - label: "Bilder"
                name: "images"
                widget: image
                multiple: true
                allow_add: true
                default: []
          - { label: "Inhalt", name: "body", widget: "markdown", required: false }
  - name: "pages"
    label: "Einzelseiten"
    create: true
    folder: "content/de/pages"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "aufnahme"
    label: "Aufnahme"
    folder: "content/de/aufnahme"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "schule"
    label: "Schule"
    folder: "content/de/schule"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "elternengagement"
    label: "Elternengagement"
    folder: "content/de/schule/elternengagement"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "konzept"
    label: "Konzept"
    folder: "content/de/schule/konzept"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "mariamontessori"
    label: "Maria Montessori"
    folder: "content/de/schule/konzept/maria-montessori"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "schulhaus"
    label: "Schulhaus"
    folder: "content/de/schule/schulhaus"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "spenden"
    label: "Spenden"
    folder: "content/de/spenden"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "verein"
    label: "Verein"
    folder: "content/de/verein"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
